name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/upload-artifact@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build APK
      run: ./gradlew assembleDebug
    - - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
      name: gpssetter-apk
      path: app/build/outputs/apk/debug/app-debug.apk

