name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build APK
        run: ./gradlew assembleDebug
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: gpssetter-apk
          path: app/build/outputs/apk/debug/*.apk
